In [ ]:
f=open("demo.txt","a")
f.write(" hyello")
f.close()

In [ ]:
f=open("KS.txt","w")
f.write("hai")
f.close()

In [ ]:
f=open("KS.txt","a")
f.write("hai")
f.close()

In [ ]:
f=open("KS.txt","r")
read=f.read()
print(read)
f.close()

haihai


In [ ]:
pip install numpy

In [ ]:
a=np.array([])
a

array([], dtype=float64)

In [ ]:
a=np.array([],int)
a

array([], dtype=int64)

In [ ]:
a=np.array([3,0,8],int)
a

array([3, 0, 8])

In [ ]:
a[0]

3

In [ ]:
a.ndim

1

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a[0:-1]

array([3, 0])

In [ ]:
b=np.array([[1,2],[2,3],[3,4]])


In [ ]:
b.ndim

2

In [ ]:
b[0,0]

1

In [ ]:
b[0]

array([1, 2])

In [ ]:
b[1]

array([2, 3])

In [ ]:
b[2]

array([3, 4])

In [ ]:
b[1,1]

3

In [ ]:
#zeros
z=np.zeros((1,2))
z

array([[0., 0.]])

In [ ]:
#ones
o=np.ones((2,2))
o

array([[1., 1.],
       [1., 1.]])

In [ ]:
f=np.full((2,2),30)
f

array([[30, 30],
       [30, 30]])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#range(start,end,step)
np.arange(3,9,2)

array([3, 5, 7])

In [ ]:
np.random.random(3)

array([0.27776503, 0.51265915, 0.68581485])

In [ ]:
np.random.randint(1,3,5)

array([2, 1, 2, 2, 2])

In [ ]:
np.random.randint(1,5,(3,4))

array([[3, 1, 2, 4],
       [1, 4, 4, 2],
       [3, 1, 2, 2]])

In [ ]:
a=np.random.randint(1,5,(3,4))
a.shape

(3, 4)

In [ ]:
a=np.array([1,2])
b=np.array([2,3])
np.add(a,b)

array([3, 5])

In [ ]:
np.append(a,5)
np.append(a,[4,5,6])

array([1, 2, 4, 5, 6])

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.insert(b,1,2,axis=1)

array([[1, 2, 2, 3],
       [4, 2, 5, 6],
       [7, 2, 8, 9]])

In [ ]:
c=np.array([1,2,3])
np.insert(c,1,10)

array([ 1, 10,  2,  3])

In [ ]:
np.delete(b,2,axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
k=np.arange(8,30)
k.reshape(3,5,6)

ValueError: cannot reshape array of size 22 into shape (3,5,6)