In [ ]:
import numpy as np

In [ ]:
k=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(k)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.insert(k,1,2,axis=0)

array([[1, 2, 3],
       [2, 2, 2],
       [4, 5, 6]])

In [ ]:
np.insert(k,1,2,axis=1)

array([[1, 2, 2, 3],
       [4, 2, 5, 6]])

In [ ]:
np.delete(k,1,axis=0)

array([[1, 2, 3]])

In [ ]:
S=np.zeros((2,2),int)
S

array([[0, 0],
       [0, 0]])

In [ ]:
S[0::,0::]=8
S

array([[8, 8],
       [8, 8]])

In [ ]:
S[::1,::1]=8
S

array([[8, 8],
       [8, 8]])

In [ ]:
S[::1,::1]=1
S

array([[1, 1],
       [1, 1]])

In [ ]:
N=np.zeros((5,5),int)
N

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
N[0:5,0:5]=5
N[1:4,1:4]=3
N[2:3,2:3]=1
N

array([[5, 5, 5, 5, 5],
       [5, 3, 3, 3, 5],
       [5, 3, 1, 3, 5],
       [5, 3, 3, 3, 5],
       [5, 5, 5, 5, 5]])

pandas

In [ ]:
import pandas as pd
S={"name":["Chittu","Mittu","Pottu"],"age":["18","18","18"],"roll no.":["29","28","27"]}
S
pd.DataFrame(S)

name age roll no.
0  Chittu  18       29
1   Mittu  18       28
2   Pottu  18       27

In [ ]:
import pandas as pd
S={"name":("Chittu","Mittu","Pottu"),"age":("18","18","18"),"roll no.":("29","28","27")}
S
pd.DataFrame(S)

name age roll no.
0  Chittu  18       29
1   Mittu  18       28
2   Pottu  18       27